[project]
name = "darkweb-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "httpx[socks]>=0.28.1",
    "rich>=14.0.0",
    "ruff>=0.11.5",
    "sqlalchemy>=2.0.40",
]
